HOST_IP=127.0.0.1
HAZELCAST_VERSION=5.1.2
PS_NAME=hazelcast

docker run --rm -d --name $PS_NAME \
-e HZ_NETWORK_PUBLICADDRESS=$HOST_IP:5701 \
-p 5701:5701 \
-e HZ_CLUSTERNAME=dev \
-e HZ_NETWORK_PORT_AUTOINCREMENT=true \
-e HZ_NETWORK_PORT_PORTCOUNT=100 \
-e HZ_NETWORK_PORT_PORT=5701 \
hazelcast/hazelcast:$HAZELCAST_VERSION
