HOST_IP=192.168.29.187
HAZELCAST_VERSION=5.1.2
PS_NAME=hazelcast

docker run --rm -d --name $PS_NAME \
-e HZ_NETWORK_PUBLICADDRESS=$HOST_IP:5701 \
--net host \
-e HZ_CLUSTERNAME=dev \
-e HZ_NETWORK_PORT_AUTOINCREMENT=true \
-e HZ_NETWORK_PORT_PORTCOUNT=100 \
-e HZ_NETWORK_PORT_PORT=5701 \
-e MANCENTER_URL=$HOST_IP:38080/mc \
hazelcast/hazelcast:$HAZELCAST_VERSION
